language: php

sudo: false
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - stable

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
      dist: precise
    - php: 5.6
      env: WP_VERSION=4.7 WP_MULTISITE=0
      dist: precise
    - php: 5.6
      env: WP_VERSION=4.6 WP_MULTISITE=0
      dist: precise
    - php: 5.6
      env: WP_VERSION=4.5 WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
      dist: precise
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.8 WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.7 WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.6 WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.5 WP_MULTISITE=0
      dist: precise

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script:
  - phpunit --coverage-clover=coverage.xml
  - ./bin/run-e2e-tests.sh || exit 1
  
after_success:
  - bash <(curl -s https://codecov.io/bash)